### ISSUE TITLE
дублюючі стилі

### ISSUE THREAD

**Issue by pecourses** [MrLipa2496/HW_3#2]
https://github.com/MrLipa2496/HW_3/blob/43d67fdb13c4057371e825ab4e6139b3eb275c55/assets/css/style.css#L42-L55
- якщо у схожих елементів частина чсилів дублюється, то для уникнення дублювання гарною практикою є ці стилі описувати разом:
```css
.p-white-text-brown-bg {
  background: #926239;
  color: #f4f4f4;
}

.p-brown-text-white-bg {
  color: #926239;
}

.p-white-text-brown-bg,
.p-brown-text-white-bg {
  font-size: 17px;
  padding: 20px;
  line-height: 1.6;
}

```
